CREATE TABLE IF NOT EXISTS resident (
Id VARCHAR(64) PRIMARY KEY, 
Email VARCHAR(64) NOT NULL, 
Name VARCHAR(64) NOT NULL,
Telephone VARCHAR(11) NOT NULL, 
Apto INTEGER NOT NULL,
Created DATETIME NOT NULL,
Updated DATETIME);
